=== artem-yam/xml_jaxp_task/src/main/resources/chat.xsd
<?xml version='1.0' encoding='UTF-8' ?>
<schema xmlns:chat="http://www.epam.com/jtc/chat"
        xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.com/jtc/chat"
        elementFormDefault="qualified" attributeFormDefault="unqualified">
    <element name="chat">
        <complexType>
            <sequence>
                <element name="message" type="chat:message" minOccurs="0"
                         maxOccurs="unbounded"/>
                <element name="status" type="chat:status" minOccurs="0"
                         maxOccurs="unbounded"/>
                <element name="role" type="chat:role" minOccurs="0"
                         maxOccurs="unbounded"/>
                <element name="user" type="chat:user" minOccurs="0"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>

        <key name="role_key">
            <selector xpath="chat:role"/>
            <field xpath="chat:title"/>
        </key>
        <keyref name="user_role_key" refer="chat:role_key">
            <selector xpath="chat:user"/>
            <field xpath="chat:role"/>
        </keyref>

        <key name="status_key">
            <selector xpath="chat:status"/>
            <field xpath="chat:title"/>
        </key>
        <keyref name="message_status_key" refer="chat:status_key">
            <selector xpath="chat:message"/>
            <field xpath="chat:status"/>
        </keyref>

        <key name="user_key">
            <selector xpath="chat:user"/>
            <field xpath="chat:nick"/>
        </key>
        <keyref name="message_user_key" refer="chat:user_key">
            <selector xpath="chat:message"/>
            <field xpath="chat:user_from"/>
        </keyref>

    </element>

    <complexType name="message">
        <sequence>
            <element name="user_from" type="IDREF"/>
            <element name="time_stamp" type="dateTime"/>
            <element name="message" type="string"/>
            <element name="status" type="IDREF"/>
        </sequence>
    </complexType>

    <complexType name="status">
        <sequence>
            <element name="title">
                <simpleType>
                    <restriction base="ID">
                        <enumeration value="LOGIN"/>
                        <enumeration value="MESSAGE"/>
                        <enumeration value="KICK"/>
                        <enumeration value="LOGOUT"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="description" type="string"/>
        </sequence>

    </complexType>
    <complexType name="role">
        <sequence>
            <element name="title">
                <simpleType>
                    <restriction base="ID">
                        <enumeration value="ADMIN"/>
                        <enumeration value="USER"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="description" type="string"/>
        </sequence>

    </complexType>
    <complexType name="user">
        <sequence>
            <element name="nick" type="ID"/>
            <element name="role" type="string"/>
        </sequence>
    </complexType>

</schema>

=== artem-yam/xml_jaxp_task/src/main/resources/chat.xml
<?xml version='1.0' encoding='UTF-8' ?>
<chat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.epam.com/jtc/chat"
      xsi:schemaLocation="http://www.epam.com/jtc/chat chat.xsd">
    <message>
        <user_from>User1</user_from>
        <time_stamp>2002-05-30T09:30:10Z</time_stamp>
        <message></message>
        <status>MESSAGE</status>
    </message>
    <message>
        <user_from>User1</user_from>
        <time_stamp>2002-05-30T09:30:10Z</time_stamp>
        <message></message>
        <status>LOGIN</status>
    </message>
    <status>
        <title>LOGIN</title>
        <description>User logged in</description>
    </status>
    <status>
        <title>MESSAGE</title>
        <description>User sent message</description>
    </status>
    <status>
        <title>KICK</title>
        <description>User was kicked</description>
    </status>
    <status>
        <title>LOGOUT</title>
        <description>Used logged out</description>
    </status>
    <role>
        <title>ADMIN</title>
        <description>admin</description>
    </role>
    <role>
        <title>USER</title>
        <description>common user</description>
    </role>
    <user>
        <nick>User1</nick>
        <role>USER</role>
    </user>

</chat>
